config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'users#home'
  get '/home/about' => 'users#about', as: "about"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end
      

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    if @book.save
      flash[:notice] = "Book was created successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was updated successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_like.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <span class="fa fa-heart" aria-hidden="true" style="color: red;"></span>
    <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <span class="fa fa-heart-o" aria-hidden="true"></span>
    <%= book.favorites.count %>
    <% end %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Book</h1>
  <%= render 'partial/error_msg', obj: @book %>
  <%= form_with model: @book do |f| %>
  <div class="field row">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title, value: @book.title, class: "col-xs-12 book_title" %>
  </div>
  <div class="field row">
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body, value: @book.body, class: "col-xs-12 book_body" %>
  </div>
  <div class="actions row">
  <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
  </div>
  <% end %>
  <%= link_to "Show", book_path(params[:id]) %>
  |
  <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'partial/error_msg', obj: @book %>
<%= render 'partial/userinfo', book: @book, user: current_user%>
<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
            <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        
        <td id="like-<%= book.id %>">
          <%= render 'like', book: book %>
        </td>

        <td>
            コメント数：
            <%= book.book_comments.count %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  


</div>

app/views/books/show.html.erb
<%= render 'partial/userinfo', book: @new, user: @user %>
<div class="col-xs-9">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <% if current_user.id == @user.id %>
      <tr>
        <td>
        <%= link_to user_path(@user) do %>
        <%= attachment_image_tag @book.user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
        <br>
        <%= @user.name %>
        <% end %>
        </td>
        <td>
        <%= link_to book_path(params[:id]) do %>
        <%= @book.title %>
        <% end %>
        </td>
        <td><%= @book.body %></td>
        <td id="like-<%= @book.id %>">
        <%= render "like", book: @book %>
        </td>
        <td>
          コメント数：
          <%= @book.book_comments.count %>
        </td>
        <td>
          <%= link_to "Edit", edit_book_path(params[:id]), class: "btn-sm btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
        </td>
      </tr>
      <% else %>
      <tr>
        <td>
        <%= link_to user_path(@user) do %>
        <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
        <br>
        <%= @user.name %>
        <% end %>
        </td>
        <td>
        <%= link_to book_path(params[:id]) do %>
        <%= @book.title %>
        <% end %>
        </td>
        <td><%= @book.body %></td>
        <td id="like-<%= @book.id %>">
        <%= render "like", book: @book %>
        </td>
        <td>
          コメント数：
          <%= @book.book_comments.count %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <table id="comment_table">
    <% @book.book_comments.each do |book_comment| %>
        <%= render 'book_comments/comment', book_comment: book_comment %>
    <% end %>
  </table>
  <%= form_with(model:[@book, @book_comment]) do |f| %>
    <div class="col-xs-9 my-4">
      <%= f.text_area :comment, class: "form-control" %>
    </div>
    <%= f.submit "送信" %>
  <% end %>
</div>