config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  root 'users#home'
  get '/home/about' => 'users#about', as: "about"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f8452db4da.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left"><span>Bookers</span></nav>
        <nav class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
            <% end %>
            </li>
            <li>
            <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user users" aria-hidden="true"> Users</span>
            <% end %>
            </li>
            <li>
            <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books" aria-hidden="true"> Books</span>
            <% end %>
            </li>
            <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout" aria-hidden="true"> logout</span>
            <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to '/' do %>
              <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
            <% end %>
            </li>
            <li>
            <%= link_to about_path do %>
              <span class="glyphicon glyphicon-link about" aria-hidden="true"> About</span>
            <% end %>
            </li>
            <li>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit sign_up" aria-hidden="true"> sign up</span>
            <% end %>
            </li>
            <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in login" aria-hidden="true"> login</span>
            <% end %>
            </li>
          </ul>
        <% end %>
        </nav>
      </div>
    </header>
    <div class="body">
      <div class="container">
        <p id="notice"><%= notice %></p>
          <div class="row">
          <%= yield %>
          </div>
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9"><p>CpoyRight Infratop.inc</p></div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>